/**

Create a function that takes the age and return the age in days.

ExamplescalcAge(65) ➞ 23725
calcAge(0) ➞ 0
calcAge(20) ➞ 7300

Notes
Use 365 days as the length of a year for this challenge.
Ignore leap years and days between last birthday and now.
Expect only positive integer inputs.

**/

function calcAge(age) {
	
}

/**
function calculate_age(dob) { 
    var diff_ms = Date.now() - dob.getTime();
    var age_dt = new Date(diff_ms); 
  
}

console.log(calculate_age(new Date(1982, 11, 4)));


**/
